# Generated by Django 4.2 on 2023-05-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='emp_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
