# Generated by Django 4.2 on 2023-05-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_appointmentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
